export const images: Record<string, string> = {
  "Paris 1564": "https://i.imgur.com/OtLizob.jpeg",
  "Paris 1565": "https://i.imgur.com/aWMwpYR.jpeg",
  "Paris 1566a": "https://i.imgur.com/77rBnaY.jpeg",
  "Paris 1598a": "https://i.imgur.com/pRgutf1.png",
  "Paris 1605": "https://i.imgur.com/OXNVRyx.png",
  "Paris 1609": "https://i.imgur.com/uh46Q0V.jpeg",
  "Paris 1610": "https://i.imgur.com/JnjkxOZ.jpeg",
  "Geneva 1611": "https://i.imgur.com/whVVkqs.jpeg",
  "Paris 1613": "https://i.imgur.com/MO2gGL6.jpeg",
  "Paris 1615": "https://i.imgur.com/Xck3ehW.jpeg",
  "Paris 1621": "https://i.imgur.com/Fr8c5pu.jpeg",
  "Paris 1622": "https://i.imgur.com/rumIeIz.jpeg",
  "Paris 1624": "https://i.imgur.com/bV0PvhI.jpeg",
  "Paris 1626": "https://i.imgur.com/vJB7EZo.jpeg",
  "Geneva 1628": "https://i.imgur.com/WTo76ul.jpeg",
  "Paris 1629": "https://i.imgur.com/0hpwgeU.jpeg",
  "Paris 1631": "https://i.imgur.com/vn7S01j.png",
  "Paris 1632": "https://i.imgur.com/L90iwgJ.jpeg",
  "Paris 1632a": "https://i.imgur.com/GykxJmm.jpeg",
  "Paris 1634": "https://i.imgur.com/6PTrv6l.png",
  "Paris 1639": "https://i.imgur.com/Vt56Rdi.jpeg",
  "Paris 1640": "https://i.imgur.com/UMtbMvd.jpeg",
  "Paris 1643": "https://i.imgur.com/aGzHYA4.jpeg",
  "Paris 1644": "https://i.imgur.com/Yqm1666.jpeg",
  "Paris 1644b": "https://i.imgur.com/5xJhWBN.jpeg",
  "Lyon 1645": "https://i.imgur.com/fP6pLCa.jpeg",
  "Paris 1652": "https://i.imgur.com/7iHX9L3.png",
  "Paris 1654a": "https://i.imgur.com/z3w7Bwb.png",
  "Rouen 1676": "https://i.imgur.com/UR9OaDX.jpeg",
  "Paris 1677a": "https://i.imgur.com/A6y55gJ.jpeg",
  "Paris 1682a": "https://i.imgur.com/5h9zMcw.jpeg",
  "Paris 1683": "https://i.imgur.com/ZcqUFvm.jpeg",
  "Rouen and Paris 1683": "https://i.imgur.com/Uelr09C.jpeg",
  "The Hague 1690": "https://i.imgur.com/GyfaBa7.png",
  "Paris 1690": "https://i.imgur.com/V8v0TqH.jpeg",
  "Amsterdam 1697": "https://i.imgur.com/bFhM7xn.jpeg",
  "Paris 1697": "https://i.imgur.com/vxNfEVb.jpeg",
  "Paris 1693": "https://i.imgur.com/TAwolqQ.png",
};
